#!/usr/bin/env python

from itertools import izip
import os
import sys

def to_dict(xs):
    dict = {}
    for x in xs:
        if len(x) > 1:
            dict[x[0]] = str(x[1])
    return dict    

def get_secrets():
    return (map(lambda x: x.rstrip('\n\r').split('='), open("secrets")))

def command_to_aws(key, user, ip):
    return "ssh -i {} {}@{}".format(key, user, ip)

def shell(command):
    print(command)
    os.system(command)

def help():
    print("")
    print("-h ... help menu")
    print("-g ... go to aws")
    print("")

secrets = to_dict(get_secrets())
key     = secrets["key"]
user    = secrets["user"]
ip      = secrets["ip"]

options = {
    "-g": command_to_aws(key, user, ip)
}

if len(sys.argv) < 2:
    help()
    sys.exit("you need argument")

command = (options.get(sys.argv[1], None))
if command == None:
    help()
else:
    shell(command)
